version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: my-project-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  quizapp:
    image: corqu/quizapp:1.8
    container_name: quizapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    restart: on-failure

  quizfront:
    image: corqu/quiz-front:1.6
    container_name: quizfront
    ports:
      - "3000:3000"
    depends_on:
      - quizapp
